name: CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]
    types: [opened, synchronize]

jobs:
  styleslint:
    name: Style code css
    runs-on: ubuntu-18.04

    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install packages
        run: npm install
      - name: Run Stylelint
        run: npm run lint:styles --fix